name: Deploy Eficare to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build client
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Copy client build to server
        run: |
          rm -rf server/build
          cp -r client/build server/build

      - name: Set up environment variables
        run: |
          echo "TRANSPORTER_PASSWORD=${{ secrets.TRANSPORTER_PASSWORD }}" >> $GITHUB_ENV
          echo "TRANSPORTER_LOGIN=${{ secrets.TRANSPORTER_LOGIN }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set dynamic version tag (date + short commit)
      - name: Set up IMAGE_TAG
        id: vars
        run: echo "IMAGE_TAG=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and Push Docker image
        run: |
          cd server
          docker build -t abhishekvijay20/eficare:${{ env.IMAGE_TAG }} .
          docker push abhishekvijay20/eficare:${{ env.IMAGE_TAG }}

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/eficare:${{ env.IMAGE_TAG }}
            
            # Check if the container exists before stopping/removing
            docker ps -a | grep eficare-container && docker stop eficare-container || true
            docker ps -a | grep eficare-container && docker rm eficare-container || true

            docker run -d --name eficare-container -p 5000:5000 \
              -e TRANSPORTER_PASSWORD=${{ secrets.TRANSPORTER_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/eficare:${{ env.IMAGE_TAG }}