name: Eficare.js CI

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust the Node.js version as needed

    - name: Install dependencies for client
      working-directory: client
      run: npm install

    - name: Build React app
      working-directory: client
      run: npm run build

    - name: Rename build folder to static and move to server
      run: |
        rm -rf server/static         
        mv client/build server/static

    - name: Install dependencies for server
      working-directory: server
      run: npm install

    - name: Archive production artifacts
      run: tar -czf server_build.tar.gz -C server .

    - name: Remove existing archive file and extracted files on DigitalOcean droplet
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_KEY }}
        SSH_HOST: 159.65.140.114
        SSH_USER: root
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST 'rm -f /var/www/eficare/server_build.tar.gz && rm -rf /var/www/eficare/*'

    - name: Copy files via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_KEY }}
        SSH_HOST: 159.65.140.114
        SSH_USER: root
      run: |
        scp -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa server_build.tar.gz $SSH_USER@$SSH_HOST:/var/www/eficare

    - name: Deploy on DigitalOcean
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_KEY }}
        SSH_HOST: 159.65.140.114
        SSH_USER: root
      run: |
        ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << EOF
          cd /var/www/eficare
          tar -xzf /var/www/eficare/server_build.tar.gz -C .
          npm install --production
          pm2 stop all
          pm2 server.js
        EOF
