name: Deploy Eficare to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Copy files to the droplet
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_KEY }}
          SSH_HOST: ${{ secrets.SERVER_IP }}
          SSH_USER: root
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
          # Copy all the files (including docker-compose.yml and app source)
          scp -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./ $SSH_USER@$SSH_HOST:/var/www/eficare

      - name: SSH to DigitalOcean and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_KEY }}
          SSH_HOST: ${{ secrets.SERVER_IP }}
          SSH_USER: root
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
          
          # SSH into the droplet and run the commands
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << 'EOF'
            cd /var/www/eficare
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF
